"""empty message

Revision ID: 09d832c9c655
Revises: 69e291813f9b
Create Date: 2022-04-11 18:17:26.183101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09d832c9c655'
down_revision = '69e291813f9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('watch_check', 'link')
    op.drop_column('watch_check', 'score')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watch_check', sa.Column('score', sa.FLOAT(), nullable=True))
    op.add_column('watch_check', sa.Column('link', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
