"""'add_wish_list_and_archive_to_user'

Revision ID: 0a4415c3e310
Revises: 0c36e5be7b74
Create Date: 2022-03-28 20:35:08.636548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a4415c3e310'
down_revision = '0c36e5be7b74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('wish_list', sa.String(), nullable=True))
    op.add_column('users', sa.Column('archive', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'archive')
    op.drop_column('users', 'wish_list')
    # ### end Alembic commands ###
