"""empty message

Revision ID: 3576a0da87c7
Revises: 0a4415c3e310
Create Date: 2022-04-09 15:21:33.766459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3576a0da87c7'
down_revision = '0a4415c3e310'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('film', sa.Column('film_length', sa.Integer(), nullable=True))
    op.drop_column('film', 'link')
    op.add_column('serial', sa.Column('series_length', sa.Integer(), nullable=False))
    op.drop_column('serial', 'link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('serial', sa.Column('link', sa.VARCHAR(), nullable=True))
    op.drop_column('serial', 'series_length')
    op.add_column('film', sa.Column('link', sa.VARCHAR(), nullable=True))
    op.drop_column('film', 'film_length')
    # ### end Alembic commands ###
