"""empty message

Revision ID: 4929d5539a7c
Revises: 09d832c9c655
Create Date: 2022-04-12 00:30:19.608727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4929d5539a7c'
down_revision = '09d832c9c655'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('watch_check', 'season_num',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('watch_check', 'eps_num',
               existing_type=sa.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('watch_check', 'eps_num',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('watch_check', 'season_num',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
