"""empty message

Revision ID: 69e291813f9b
Revises: 9d0b1a1244a3
Create Date: 2022-04-11 18:16:32.482434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69e291813f9b'
down_revision = '9d0b1a1244a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('serial', sa.Column('eps', sa.Integer(), nullable=False))
    op.add_column('serial', sa.Column('eps_length', sa.Integer(), nullable=False))
    op.add_column('serial', sa.Column('date_add', sa.DateTime(), nullable=True))
    op.drop_column('serial', 'series_length')
    op.drop_column('serial', 'series')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('serial', sa.Column('series', sa.INTEGER(), nullable=False))
    op.add_column('serial', sa.Column('series_length', sa.INTEGER(), nullable=False))
    op.drop_column('serial', 'date_add')
    op.drop_column('serial', 'eps_length')
    op.drop_column('serial', 'eps')
    # ### end Alembic commands ###
