"""empty message

Revision ID: c84171940f52
Revises: 3576a0da87c7
Create Date: 2022-04-09 15:24:09.549024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c84171940f52'
down_revision = '3576a0da87c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('film', sa.Column('length', sa.Integer(), nullable=True))
    op.drop_column('film', 'film_length')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('film', sa.Column('film_length', sa.INTEGER(), nullable=True))
    op.drop_column('film', 'length')
    # ### end Alembic commands ###
