"""empty message

Revision ID: d2af19a46c73
Revises: c84171940f52
Create Date: 2022-04-09 15:25:51.367166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2af19a46c73'
down_revision = 'c84171940f52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('film_info', 'score')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('film_info', sa.Column('score', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
